# Generated by Django 4.2.4 on 2023-11-14 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='description',
            new_name='descripcion',
        ),
    ]
